import { useState, useEffect } from "react"
import Head from 'next/head'
import { getSession, signIn } from "next-auth/react"
import styles from '../styles/dashboard.module.css'
import 'bootstrap/dist/css/bootstrap.css'
import Link from "next/link"

function Dashboard(){
  const[loading, setLoading] = useState(true)
  const [data, setData] = useState([])

  useEffect(()=>{
    const securePage = async () =>{
      const session = await getSession()
      if(!session){
        signIn()
      }
      else{
        setLoading(false)
      }
    }
    securePage()
  },[])

  useEffect(() => {
    setLoading(true)
    fetch('/api/blogs')
      .then((res) => res.json())
      .then((data) => {
        setData(data)
        setLoading(false)
      })
  }, [])

  if(loading){
    return <h2>Loading...</h2>
  }

  const deletecomment = async (commentId) => {
    const response = await fetch(`/api/comments/${commentId}`, {
        method : 'DELETE',
    })
    const data  =  await response.json()
    console.log(data)
    fetchComments()
}


return (
  <>
<Head>
        <title>Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
  <div className={styles.container}>

  <Link href='/blog'>
  <button type="button" className={styles.btn}>create</button>
  </Link>

     {data.map((blog) =>{
      return (
          <div key={blog.id}>
              <h1>{blog.title}</h1>
              <p>{blog.desc}</p>
              <hr/>
          </div>
      )
     })}
  </div>
  </>
)

}

export default Dashboard
